echo Build environment configuration BASH script.

SOURCE_PATH="$(dirname ${BASH_SOURCE[0]})"
echo Source path=$SOURCE_PATH

ABS_SOURCE_PATH=$(realpath $SOURCE_PATH)
echo Absolute Source path=$ABS_SOURCE_PATH

CWD=`pwd`
echo Current working directory=$CWD

SETUP_SHELL_BASH="setup_shell.bash"
touch $SETUP_SHELL_BASH

MAKE_CONFIG="config.makefile"
touch $MAKE_CONFIG
echo "# Autogenerated MAKE configuration" > $MAKE_CONFIG
echo "SOURCE_PATH:=$SOURCE_PATH" >> $MAKE_CONFIG

MAKEFILE="Makefile"
touch $MAKEFILE

echo "include $MAKE_CONFIG" > $MAKEFILE
echo "-include custom.config.makefile" >> $MAKEFILE
echo "include $SOURCE_PATH/build/Makefile" >> $MAKEFILE

echo "SOURCE_PATH=$SOURCE_PATH" > $SETUP_SHELL_BASH

GCC_PATH=`which gcc`
echo GCC=$GCC_PATH

ERLC_PATH=`which erlc`
echo ERLC=$ERLC_PATH
echo "ERLC:=$ERLC_PATH" >> $MAKE_CONFIG

ERL_PATH=`which erl`
echo ERL=$ERL_PATH
echo "ERL:=$ERL_PATH" >> $MAKE_CONFIG

JAVAC_PATH=`which javac`
echo JAVAC=$JAVAC_PATH
echo "JAVAC:=$JAVAC_PATH" >> $MAKE_CONFIG

SCALAC_PATH=`which scalac`
echo SCALAC=$SCALAC_PATH
echo "SCALAC:=$SCALAC_PATH" >> $MAKE_CONFIG

FASTSCALAC_PATH=`which fsc`
echo FASTSCALAC=$FASTSCALAC_PATH
echo "FASTSCALAC:=$FASTSCALAC_PATH" >> $MAKE_CONFIG

