# Call this script from a build directory.
# It creates proxy Makefile that inlcudes Makefile from the source directory.
#

echo Build environment configuration BASH script.



CWD=`pwd`
echo Current working directory=$CWD

SOURCE_PATH="$(dirname ${BASH_SOURCE[0]})"
echo Source path=$SOURCE_PATH

ABS_SOURCE_PATH=$(realpath $SOURCE_PATH)
echo Absolute Source path=$ABS_SOURCE_PATH

MAKE_CONFIG="config.makefile"

MAKEFILE="Makefile"
echo "include $MAKE_CONFIG" > $MAKEFILE
echo "include $SOURCE_PATH/bld/Makefile" >> $MAKEFILE


echo "# Autogenerated MAKE configuration" > $MAKE_CONFIG
echo "SOURCE_PATH:=$SOURCE_PATH" >> $MAKE_CONFIG
echo "ABS_SOURCE_PATH:=$ABS_SOURCE_PATH" >> $MAKE_CONFIG

BUILD_DIR=$CWD
echo "BUILD_DIR:=$BUILD_DIR" >> $MAKE_CONFIG

GCC_PATH=`which gcc`
echo GCC=$GCC_PATH
echo "GCC:=$GCC_PATH" >> $MAKE_CONFIG

# At last include custom configuration.
echo "-include custom.config.makefile" >> $MAKE_CONFIG

