source 'https://rubygems.org'

gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'middleman-syntax'
gem 'redcarpet'
gem "middleman-blog", "~> 4.0"
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]
gem 'bh', '~> 1.3'

# Workaround for "LoadError: cannot load such file -- opal" when
# there is .rb somewhere inside source dir.
# https://github.com/middleman/middleman/issues/2015
gem 'opal'
