
DEF_ERROR(OK, "OK (No error)")
DEF_ERROR(NO_FILE, "No file")
//DEF_ERROR(SYMBOL_EXPECTED, "Some symbol expected")
DEF_ERROR(PARSER_CANT_HANDLE_SYMBOL, "Parser can't handle symbol")
DEF_ERROR(INVALID_SYMBOL, "Invalid symbol")
DEF_ERROR(INVALID_NUMBER, "Invalid number")
DEF_ERROR(INCOMPLETE_LIT_STRING, "Incomplete literal string, no matching \" found")
DEF_ERROR(EOL_EXPECTED, "End-Of-Line expected")
DEF_ERROR(UNEXPECTED_SYMBOL, "Unexpected symbol")
DEF_ERROR(IDENTIFIER_EXPECTED, "Identifier expected")
DEF_ERROR(BEGIN_EXPECTED, "\"{\" expected")
//DEF_ERROR(TYPE_SPECIFIER_EXPECTED, "Type specifier expected")

DEF_ERROR(KW_PACKAGE_EXPECTED, "\"package\" expected")
DEF_ERROR(KW_CLASS_EXPECTED, "\"class\" expected")
//DEF_ERROR(KW_VAL_EXPECTED, "\"val\" expected")
//DEF_ERROR(KW_FUNC_EXPECTED, "\"func\" expected")

//DEF_ERROR(COLON_EXPECTED, "\":\" expected")
//DEF_ERROR(SEMICOLON_EXPECTED, "\";\" expected")
//DEF_ERROR(ASSIGN_EXPECTED, "\"=\" expected")
